djangoecommerce/catalog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug>/', views.category, name='category'),
    path('produtos/<slug>/', views.product, name='product'),
]

djangoecommerce/djangoecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView 
from core import views


urlpatterns = [
    path('', views.index, name='index'),
    path('contato/', views.contact, name='contact'),
    path('entrar/', LoginView.as_view(template_name='login.html'), name='login'),
    path('sair/', LogoutView.as_view(next_page='index'), name='logout'),
    path('catalogo/', include('catalog.urls')),
    path('conta/', include('accounts.urls')),
    path('compras/', include('checkout.urls')),
    path('admin/', admin.site.urls),
]

djangoecommerce/accounts/models.py
import re
from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin


class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(
        'Apelido/Usuário',
        max_length=30,
        unique=True,
        validators=[
            validators.RegexValidator(
                re.compile(r'^[\w.@+-]+$'),
                'Informe um nome de usuário válido.'
                'Este valor deve conter apenas letras e números'
                'e os caracteres: @/./+/-/).',
                'invalid'            
            )
        ], help_text='Um nome curto que será' 
        'usado para indentificá-lo de forma única na plataforma'
    )
    
    name = models.CharField(
        'Nome',
        max_length=100,
        blank=True
    )

    email = models.EmailField(
        'E-mail',
        unique=True
    ) 

    is_staff = models.BooleanField(
        'Equipe',
        default=False
    )

    is_active = models.BooleanField(
        'Ativo',
        default=True
    )

    date_joined = models.DateTimeField(
        'Dada de entrada',
        auto_now_add=True
    )

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.name or self.username

    def get_full_name(self):
        return str(self)

    def get_short_name(self):
        return str(self).split(" ")[0]

djangoecommerce/catalog/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):

    name = models.CharField(
        'Nome',
        max_length=100
    )

    slug = models.SlugField(
        'Identificador',
        max_length=100
    )

    created = models.DateTimeField(
        'Criado em',
        auto_now_add=True
    )

    modified = models.DateTimeField(
        'Modificado em',
        auto_now=True
    )

    def get_absolute_url(self):
        return reverse(
            'category',
            kwargs={'slug': self.slug}
        )

    def __str__(self):
        return self.name
                               
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['name']



class Product(models.Model):

    name = models.CharField(
        'Nome',
        max_length=100
    )

    slug = models.SlugField(
        'Identificador',
        max_length=100
    )

    category = models.ForeignKey(
        'catalog.Category',
        verbose_name='Categoria',
        on_delete=models.CASCADE
    )

    description = models.TextField(
        'Descrição',
        blank=True
    )

    price = models.DecimalField(
        'Preço',
        decimal_places=2,
        max_digits=8)

    created = models.DateTimeField(
        'Criado em',
        auto_now_add=True
    )

    modified = models.DateTimeField(
        'Modificado em',
        auto_now=True
    )

    def get_absolute_url(self):
        return reverse(
            'product',
            kwargs={'slug': self.slug}
        )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']

djangoecommerce/core/models.py
from django.db import models

# Create your models here.

djangoecommerce/core/views.py
from django.shortcuts import render
from django.http import HttpResponse

from catalog.models import Category


def index(request):
    return render(request, 'index.html')

def contact(request):
    return render(request, 'contact.html')

def product(request):
    return render(request, 'product.html')
    

djangoecommerce/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Django E-Commerce{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="" class="navbar-brand">Django E-Commerce</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'index' %}">Início</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'product_list' %}" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
				{% for category in categories %}
				<li><a href="{{ category.get_absolute_url }}">{{ category }}</a></li>
				{% endfor %}
              </ul>
            </li>
			<li>
				<a href="{% url 'contact' %}">Contato</a>
			</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
			{% if user.is_authenticated %}
			<li><a href="{% url 'logout' %}">Sair</a></li>
			{% else %}
			<li><a href="{% url 'login' %}">Entrar</a></li>
			<li><a href="{% url 'register' %}">Registro</a></li>
			{% endif %}
          </ul>
        </div>
      </div>
    </div>
    <div class="container margin-top">
		{% block container %}{% endblock %}
		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
			      <li><a href="">Início</a></li>
			      <li><a href="">Produtos</a></li>
			      <li><a href="">Contato</a></li>
			      <li><a href="">Termos e Privacidade</a></li>
			    </ul>
			  </div>
			</div>
		</footer>
	</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

djangoecommerce/core/templates/contact.html
{% extends "base.html" %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Fale conosco</h1>
    <form class="form-horizontal">
        <fieldset>
            <div class="form-group">
              <label for="id_name" class="col-md-3 control-label">Nome</label>
              <div class="col-md-9">
                <input type="text" class="form-control" id="id_name" placeholder="Nome" />
              </div>
            </div>
            <div class="form-group">
              <label for="id_email" class="col-md-3 control-label">E-mail</label>
              <div class="col-md-9">
                <input type="text" class="form-control" id="id_email" placeholder="E-mail" />
              </div>
            </div>
            <div class="form-group has-error">
              <label for="id_message" class="col-md-3 control-label">Mensagem</label>
              <div class="col-md-9">
                <textarea class="form-control" rows="3" id="id_message"></textarea>
                <span class="help-block">Este campo é obrigatório</span>
              </div>
            </div>
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

djangoecommerce/core/templates/index.html
{% extends "base.html" %}

{% block container %}
<div class="jumbotron page-header">
  <h1>Django E-Commerce</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  <p><a class="btn btn-primary">Saiba mais</a></p>
</div>
{% endblock %}

djangoecommerce/core/templates/login.html
{% extends "base.html" %}

{%load widget_tweaks %}

{% block title %}Entrar | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                  <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.username class="form-control" %}
                    {% for error in form.username.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                  <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.password class="form-control" %}
                    {% for error in form.password.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}